### ISSUE TITLE
PHP7.0 and Symfony3 plan?

### ISSUE THREAD

**Issue by hmert** [GoogleCloudPlatform/appengine-symfony-starter-project#4]
Hi,
Is there a future support plan for php7.0 on appengine and symfony3?

or we have to use `SF@2.6.*` and `php@5.5` 

Thank you!

**Comment by justinleapline** [comment]
Agree. Would like to hear the answer to this.

**Comment by JustinBeckwith** [comment]
Greetings folks! We don't currently have an idea of when PHP7 will land on App Engine.  However, this is pretty easy to do today on App Engine Managed VMs.  This isn't quite production ready yet, but you can see where we're headed here:

https://github.com/GoogleCloudPlatform/php-docker/tree/master/php-nginx

**Comment by hmert** [comment]
@JustinBeckwith Thank you :) We've already use php7 in production (we're a Google Cloud Premier Partner and Docker Lover). If there is  beta release of app engine with php7, count us in! :)

**Comment by titolendable** [comment]
@JustinBeckwith what about sf3?

**Comment by abdielcs** [comment]
At least symfony 2.7, since 2.6 is not a long term support version and is not maintained any more.
